eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka
server:
    name: api-gateway
    port: 3221
spring:
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
                - id: baeldung_route
                  uri: http://baeldung.com
                  predicates:
                      - Path=/baeldung/
                - id: app_chat
                  uri: http:localhost:8001
                  predicates:
                      - Path=/app_chat/
    main:
        web-application-type: reactive
management:
    endpoints:
        web:
            exposure:
                include: "*"