eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka
management:
    endpoints:
        web:
            exposure:
                include: '*'
server:
    name: api-gateway
    port: 3221
spring:
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                lowerCaseServiceId: true
            routes:
                - id: app-chat
                  uri: http://localhost:8001/
                  predicated: path=/app-chat/**
    main:
        web-application-type: reactive
