eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka
server:
    name: api-gateway
    port: 3221
spring:
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
#            routes:
#                - id: baeldung_route
#                  uri: http://baeldung.com
#                  predicates:
#                      - Path=/baeldung/
    main:
        web-application-type: reactive
#management:
#    endpoints:
#        web:
#            exposure:
#                include: "*"