eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka
server:
    name: api-gateway
    port: 3221
spring:
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
        web-application-type: reactive
management:
    endpoints:
        web:
            exposure:
                include: "*"