spring:
  datasource:
    url: dbc:postgresql://localhost:5432/appchat
    username: postgres
    password: postgres
    initialize: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  hibernate:
    ddl-auto: update
    show-sql: true
  application:
    name: app-chat
server:
  port: 8001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true