spring:
    datasource:
        initialize: true
        password: qwejor#@asd32453hqjwejrfhkjqw
        url: jdbc:postgresql://plannewsbanner_db:5432/banner
        username: njasdqwe
    jpa:
        hibernate:
            ddl-auto: update
            show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
