eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
server:
    port: 8003
spring:
    datasource:
        initialize: true
        password: postgres
        url: jdbc:postgresql://localhost:5432/ibrokers_bourse
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
            show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                # show sql
                shoe_sql: true
                use_sql_comments: true
                format_sql: true
logging:
    level:
        org.hibernate.SQL: DEBUG
        org.hibernate.type: TRACE