spring:
    datasource:
        initialize: true
        password: qwejor#@asd32453hqewqjwejrfhkjqw
        url: jdbc:postgresql://localhost:5433/bourse
        username: nja32sdqwe
    jpa:
        hibernate:
            ddl-auto: update
            show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
