server:
    port: 8001
spring:
    datasource:
        initialize: true
        password: postgres
        url: jdbc:postgresql://localhost:5432/authentication
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
            show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
