eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
server:
    port: 8005
spring:
    datasource:
        initialize: true
        password: postgres
        url: jdbc:postgresql://localhost:5432/common
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
            show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
